name       : talloc
version    : 2.3.1
release    : 11
source     :
    - https://www.samba.org/ftp/talloc/talloc-2.3.1.tar.gz : ef4822d2fdafd2be8e0cabc3ec3c806ae29b8268e932c5e9a4cd5585f37f9f77
license    : LGPL-3.0-or-later
component  : programming
summary    : Talloc is a hierarchical, reference counted memory pool system with destructors
description: |
    Talloc is a hierarchical, reference counted memory pool system with destructors
setup      : |
    %configure \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
# check      : |
# Don't bother with this as the python stuff will break
#     %make check
