name       : talloc
version    : 2.1.9
release    : 5
source     :
    - https://www.samba.org/ftp/talloc/talloc-2.1.9.tar.gz : f0aad4cb88a3322207c82136ddc07bed48a37c2c21f82962d6c5ccb422711062
license    : LGPL-3.0
component  : programming
summary    : Talloc is a hierarchical, reference counted memory pool system with destructors
description: |
    Talloc is a hierarchical, reference counted memory pool system with destructors
setup      : |
    %patch -p1 < $pkgfiles/fix_test_path.patch
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
