name       : talloc
version    : 2.1.8
release    : 1
source     :
    - https://www.samba.org/ftp/talloc/talloc-2.1.8.tar.gz : 22d14911164d4de67ff76b5269fa5250d01f78c955bc77e28615350996877130
license    : GPL-3.0
component  : programming
summary    : Talloc is a hierarchical, reference counted memory pool system with destructors
description: |
    Talloc is a hierarchical, reference counted memory pool system with destructors
builddeps  :
    - gcc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
