name       : talloc
version    : 2.2.0
release    : 10
source     :
    - https://www.samba.org/ftp/talloc/talloc-2.2.0.tar.gz : 5c6f6a45ef96b3fd0b28942673a68d0c6af5dcca9d676a2e4d57ce7e86c22ebc
license    : LGPL-3.0-or-later
component  : programming
summary    : Talloc is a hierarchical, reference counted memory pool system with destructors
description: |
    Talloc is a hierarchical, reference counted memory pool system with destructors
setup      : |
    %configure \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
# check      : |
# Don't bother with this as the python stuff will break
#     %make check
