name       : talloc
version    : 2.1.10
release    : 6
source     :
    - https://www.samba.org/ftp/talloc/talloc-2.1.10.tar.gz : c985e94bebd6ec2f6af3d95dcc3fcb192a2ddb7781a021d70ee899e26221f619
license    : LGPL-3.0
component  : programming
summary    : Talloc is a hierarchical, reference counted memory pool system with destructors
description: |
    Talloc is a hierarchical, reference counted memory pool system with destructors
setup      : |
    %patch -p1 < $pkgfiles/fix_test_path.patch
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
