name       : talloc
version    : 2.1.13
release    : 7
source     :
    - https://www.samba.org/ftp/talloc/talloc-2.1.13.tar.gz : 84f399dbf0ad97006a2b4953ea99452d033faac15aabfddd4ba61734764c6047
license    : LGPL-3.0
component  : programming
summary    : Talloc is a hierarchical, reference counted memory pool system with destructors
description: |
    Talloc is a hierarchical, reference counted memory pool system with destructors
setup      : |
    %patch -p1 < $pkgfiles/fix_test_path.patch
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace \
               --disable-rpath-install
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
